name: Release Statistically Linked Rust Binary

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install cross
        run: cargo install cross

      - name: Build with Cross
        run: cross build --release --target aarch64-unknown-linux-musl

      - name: Create Release Archive
        run: |
          cd target/aarch64-unknown-linux-musl/release
          tar -czf release-aarch64.tar.gz

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aarch64-binary
          path: target/aarch64-unknown-linux-musl/release/release-aarch64.tar.gz
